### ISSUE TITLE
plantuml example

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended_docs#5] opened 2021-03-07 18:36 UTC
I cannot figure out how to use plantuml. I have a version installed locally and it works and I've set the `plantuml` path in my user settings. I looked up some other examples on the web and guessed it would be something like

```
#+begin_src plantuml :file output.png
title Authentication Sequence

Alice->Bob: Authentication Request
note right of Bob: Bob thinks about it
Bob->Alice: Authentication Response
#+end_src
  
#+results:
file:output.png
```

But I don't get any results when I try to run `Org Exec Srouce Block` (the console says `NOT in A Source Block, nothing to run`). Also no results when using `Org Export File As Html`.

(`Org Exec Srouce Block` is verbatim - there's a typo in there)

**Comment by ihdavids** [comment] 2021-03-08 03:18
The results should get inserted (along with any errors) when you run the source block.
Yeah, I will make a tutorial on it. plantuml is actually an extension module for source blocks and doesn't have wonderful error handling. (You can write your own extension modules in the User folder, I have a couple of built in ones that I use for testing)

I will see if I can improve the error handling in there as well.

**Comment by ihdavids** [comment] 2021-03-08 06:37
I added diagrams.org with me doing a little demo of using plantuml. I also added graphviz support in 1.1.22, although it is REALLY rudimentary, I'll improve that as I have time. It is also not documented.

**Comment by ihdavids** [comment] 2021-03-08 06:39
https://github.com/ihdavids/orgextended_docs/blob/master/diagrams.org

**Comment by ihdavids** [comment] 2021-03-08 07:16
1.1.23 will have better graphviz support and ditaa as well:
![image](https://user-images.githubusercontent.com/1059210/110287339-2e659600-7f9b-11eb-97c3-f97d1173c1ff.png)

**Comment by Anti-Distinctlyminty** [comment] 2021-03-08 13:02
I was testing it out and ended up with a `NotADirectoryError: [WinError 267] The directory name is invalid`.
To make sure that there's no problem with the setup I ran the plantuml from another python script and the image was generated. So it seems to be an issue with the location of the org file itself perhaps?

https://user-images.githubusercontent.com/1378483/110324260-05ceb200-8016-11eb-8d53-6187129c2678.mp4

**Comment by ihdavids** [comment] 2021-03-08 15:42
Hmmm
Have you saved the file?

I use the path of the org file to determine where to save the generated png?

**Comment by ihdavids** [comment] 2021-03-08 15:47
I can harden that a bit

**Comment by ihdavids** [comment] 2021-03-08 15:55
Hmmm. I will have to think what to do here.
If the buffer does not have a file path and you give me a relative path for the output path I will not know where to save the output file.

I can default to your user directory, but that kind of stinks.

**Comment by ihdavids** [comment] 2021-03-08 18:14
Try that. (1.1.23)
I now force save the file on you if I can and error out if I cannot.

**Comment by ihdavids** [comment] 2021-03-08 18:35
I extended the docs a little as well.
If I have time tonight I will try to add support for executing the block in places other than just the header of the block

**Comment by ihdavids** [comment] 2021-03-08 19:33
Actually, I think I just found it!
I got 1.1.22 installed on my work machine and decided I needed a chart for something. 
I think the issue is that I was stupidly using the OrgExtended packages folder as my working directory for the subprocess!

I will patch that quickly.

**Comment by ihdavids** [comment] 2021-03-08 19:36
1.1.24 will hopefully have a fix for this. Testing as a package is always a bit of a challenge.

**Comment by Anti-Distinctlyminty** [comment] 2021-03-08 19:45
> 1.1.24 will hopefully have a fix for this. Testing as a package is always a bit of a challenge.

Well I'm happy to help :)

**Comment by ihdavids** [comment] 2021-03-08 19:54
One thing I need to fix. I turned on something I did for gnu plot, which is to auto-show images when you execute a plugin that generated an image. Working with this just now in a document with multiple images I realized I am not restoring the cursor properly so you tend to jump around in the file. That us uber annoying. I will try to fix that tonight.

**Comment by ihdavids** [comment] 2021-03-08 19:55
I will probably also make that configurable. It's nice, but also disturbing if you don't want images to be shown at the moment.

**Comment by ihdavids** [comment] 2021-03-08 20:01
Okay, it's working on my work machine now. Let me know if that solved it for you once you upgrade to 1.1.24

**Comment by ihdavids** [comment] 2021-03-08 20:01
I patched up ditaa and graphviz modules as well while I was at it. 
The python and other execution plugins may suffer from that as well. I will need to test them later and patch them up if they do.

**Comment by Anti-Distinctlyminty** [comment] 2021-03-08 20:08
I got one failure as the subdir wasn't created. Is it worth putting in a `makedirs(path, exist_ok=True)`?

**Comment by ihdavids** [comment] 2021-03-08 20:21
Hmm.
This is for the output file? (IE: it was in a subdir that didn't exist?)

Yeah, we can do that, I need to share some of the bits each of these modules are using so they stay self consistent and build a little more infrastructure around them, especially to help with others wanting to write their own.

Heh. I wrote the plantuml module one morning when I had a presentation I needed to do that afternoon. There is probably a lot of finessing we could do here. Better to do what we can in the orgsourceblock.py if we can, but I am happy to keep iterating here where we can make these less obtuse for others to use.

I actually use this stuff regularly myself, but I tend to use it on my personal development machine rather than work machine and I have been more in a mode to build tools for my needs rather than making them production quality. So this will not be the last of these kinds of issues we uncover. :(

Sorry about that.

**Comment by ihdavids** [comment] 2021-03-08 20:22
NOTE: if you find you want to participate in working on the plugin yourself, I am happy to have friends join me in this endeavour.

**Comment by Anti-Distinctlyminty** [comment] 2021-03-08 20:26
> Hmm.
> This is for the output file? (IE: it was in a subdir that didn't exist?)

Yeah, for the generated png.

> Yeah, we can do that, I need to share some of the bits each of these modules are using so they stay self consistent and build a little more infrastructure around them, especially to help with others wanting to write their own.

Definitely a good idea.

> Sorry about that.

No need to apologize! And you're right that I need to start contributing, which I will try to do. I'm just no where near as fast as you at coding, but once my current workload lessens I think I will look into it, as there's a few features that I think could be handy, it's just a matter of finding the time.

**Comment by ihdavids** [comment] 2021-03-08 20:26
I have an extension system for these source blocks. The problem I have is that the way I detect and handle source block execution is through the syntax and THAT is not easily extensible without rebuilding my plugin. I do have languagelist.yaml which makes it easy to add a new source block type, but I need to finess this so other people actually CAN write their own source block handlers. 

Right now if you place a python file in User/orgsrc/mymodule.py

The system WILL load mymodule.py and COULD theoretically execute it but like I said:
#+BEGIN_SRC mymodule <params>

will not be recognized by the syntax and is thus not executable. :(

**Comment by ihdavids** [comment] 2021-03-08 20:29
This works for dynamic blocks, link protocol markers, source blocks, table functions.
IE: you could add your own handler for [[myprotocol:somelinkdata]]

But it's not very well thought out yet. My goal is to give "SOME" of the extensibility of org mode as an advanced feature here for people wanting to go beyond what I offer in the obvious ways.

**Comment by ihdavids** [comment] 2021-03-08 20:39
After finishing gnuplot support and adding advanced table support (which is something I want) I was thinking to switch to babel mode. (Thats what org mode calls these executable source blocks)

Babel comes with something that I always forget the name of. But its the system that handles the inputs to a src block. So tables, lists constant comments, or just about any named object in org land can become an input to source code.

So you can run a process that dumps a table that is piped into some python code, that produces a list that you then plot as a graph all inside an org file. It's the precursor to jupyter notebooks. IMHO a better version because your data and code are not locked inside a proprietary thing but is just text and can be exported easily to csv's python scripts and documents with just a few commands.

It gets REALLY cool when you add in TRAMP. I am hoping I can either use the SFTP plugin (Wbond) or one of the free ones (his sells for 30$) to emulate TRAMP in emacs. That is the ability to create a remote session and have your script blocks executing on remote machines with just a path. It's an amazingly powerful feature when you can have one org file that runs something on your edge nodes, dumps out the tables, finds internal nodes that are running slow, querries them and builds and outputs a nice readable report with graphs et all from one org file.

I have used that sort of thing to great advantage in the past. It's a self documenting process that can run itself and report for you... It's notes, it's code, it's your final report.

**Comment by ihdavids** [comment] 2021-03-08 20:40
Right now my "babel mode" if you want to call it that... is just pull the parameters from the header on this block and execute them. That's not really babel yet.

**Comment by ihdavids** [comment] 2021-03-08 20:53
Don't feel like you have to keep up to me in anything. I am happy for the company, discussion, and any help you feel like providing. I can and will make room for anything you want to work on. 

The code is messy and represents my learning process in sublime. It can be pretty hard to understand at times. There is a lot of duplication and a lot of crap that I just hacked that way to get it working and get back to work on whatever else I was doing at the time... I really depend on this stuff personally, so it tends to get chopped up as I find something annoying, my like my personal .emacs was when I lived in emacs. I really love a text editor that you can do that to. IMHO, we live in these things and they SHOULD be extended to work the way we want, much like we put stickers on our laptop to personalize them.

I have been hacking sublime on and off for quite some time. This plugin started as me wanting some commands to help edit text. I just kept adding stuff I wanted for my own purposes and I realized one day that others might want some of this stuff to. It also represents big periods of me moving back to emacs for a bit, or vscode, and then coming back to sublime. 

I love emacs for it's extensibility and the AMAZING plugins on the platform. Things like swiper, TRAMP, ivy/occur, projectile, etc. They are projects lovingly built by the incredible community that is the emacs community. Emacs on the other hand is a terrible hack and those hacks make it VERY difficult to modernize. It runs so poorly on windows as to be almost unusable. So I kept going back to emacs, and then coming back to sublime as I had to work on a windows box again.

vscode was just me wanting to "be like everyone else" I am working with. I tried building this plugin for vscode for a bit... It was funny just how difficult I found it. I kept finding things I had solved in sublime at somewhat great cost and I had to re-invent in vscode and I would consider switching back over and over again. When I found the Debugger plugin for sublime and Terminus I switched back again, and that is what got me looking to publish this plugin. It sat in review for many months as package control is very slow to review new / big plugins....

I am pretty sure I am in sublime to stay. It's on all the platforms I care about, is known well enough that I get fewer strange looks when I use it. It also is starting to have many of the tools I care about. I still want a swiper mode for sublime, and a quite a few other tools, but I now feel like I could build those if I can just make the time.

**Comment by ihdavids** [comment] 2021-03-08 20:55
All that to say. I am happy to have your company along for the journey. If there are things you find confusing about the plugin, just reach out. We can chat and improve it together. 

I would perfer that this thing not be "mine"
I have considered merging with the other orgmode plugin. The maintainer has told me he will consider it, but that has yet to materialize. I am happy to put your name on the plugin and share credit as well. IMHO, plugins like this are only made better with more eyes, hands, and opinions arguing about the right way to do things.

**Comment by ihdavids** [comment] 2021-03-08 21:00
Also, I will not always be able to maintain the pace at which I have been adding things. This is a season, eventually the seasons will change and I will focus on other things for a time, I will probably come back to this plugin quite regularly though as I kind of live in it.

**Comment by ihdavids** [comment] 2021-03-09 07:14
The makedir piece should be in 1.1.25

**Comment by Anti-Distinctlyminty** [comment] 2021-03-09 20:20
> All that to say. I am happy to have your company along for the journey. If there are things you find confusing about the plugin, just reach out. We can chat and improve it together.

I've attempted to get the plugin working as a directory by checking out my forked repo to `%AppData%/Sublime Text 3/Packages` and deleting, but so far no luck in actually getting it to work. I just get lots and lots of ImportErrors such as this
<details>
<summary>traceback</summary>
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\orgextended\asettings.py", line 7, in <module>
    import OrgExtended.orgutil.template as temp
ImportError: No module named 'OrgExtended'
```
</details>

As far as I can tell from the Sublime docs I've put the repo in the right place. Any idea what I'm doing wrong here?

**Comment by Anti-Distinctlyminty** [comment] 2021-03-09 20:26
> Also, I will not always be able to maintain the pace at which I have been adding things. This is a season, eventually the seasons will change and I will focus on other things for a time, I will probably come back to this plugin quite regularly though as I kind of live in it.

That is to be expected of course. The pace lately has been rather extreme. If I can manage to get it working I will, like you, just alter aspects as and when they become an issue or if I desperately need some extra functionality.

**Comment by Anti-Distinctlyminty** [comment] 2021-03-09 20:33
> Babel comes with something that I always forget the name of. But its the system that handles the inputs to a src block. So tables, lists constant comments, or just about any named object in org land can become an input to source code.
> 
> So you can run a process that dumps a table that is piped into some python code, that produces a list that you then plot as a graph all inside an org file. It's the precursor to jupyter notebooks. IMHO a better version because your data and code are not locked inside a proprietary thing but is just text and can be exported easily to csv's python scripts and documents with just a few commands.

This is super interesting to me, as that was where I was headed when asking for the plantuml example. 
I always have trouble with deadlines and dates, so I wanted a way to gather the deadlines (or other important dates) from an org file and put them into an easy to visualize timeline. Very handy when juggling a lot of different projects with many dates attached to each.

**Comment by ihdavids** [comment] 2021-03-10 06:22
> I've attempted to get the plugin working as a directory by checking out my forked repo to `%AppData%/Sublime Text 3/Packages` and deleting, but so far no luck in actually getting it to work. I just get lots and lots of ImportErrors such as this
> 
> traceback
> ``` Traceback (most recent call last): File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin m = importlib.import_module(modulename) File "./python3.3/importlib/__init__.py", line 90, in import_module File "", line 1584, in _gcd_import File "", line 1565, in _find_and_load File "", line 1532, in _find_and_load_unlocked File "", line 584, in _check_name_wrapper File "", line 1022, in load_module File "", line 1003, in load_module File "", line 560, in module_for_loader_wrapper File "", line 868, in _load_module File "", line 313, in _call_with_frames_removed File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\orgextended\asettings.py", line 7, in import OrgExtended.orgutil.template as temp ImportError: No module named 'OrgExtended' ```
> As far as I can tell from the Sublime docs I've put the repo in the right place. Any idea what I'm doing wrong here?

Okay, so my clone is here:
C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\OrgExtended

I just clone directly into that folder, dump an OrgExtended.sublime-project file in the root of that and away I go.
NOTE the capitalization, it matters... I should really NOT have done that, but it's the way it is now.

**Comment by ihdavids** [comment] 2021-03-10 06:25
1.1.26 is in the works but not ready to release. I am feeling under the weather today.

I am SLOWLY driving towards:
https://www.youtube.com/watch?v=5ViUBaarsbw

I have a columnview dynamic block built now. It dumps out a table. (You can see it in the notes for 1.1.26 which are located in the messages folder as 1.1.26.org)

I will start working in a branch if you are going to join me so I can keep my broken bits from impacting you. I have been uber lazy till now

**Comment by ihdavids** [comment] 2021-03-10 06:29
In order to achieve that Gantt chart ability I need:

1) Column View - Now happening right now... It's going to take some careful thinking and experimentation on how to make that a reality. This one is more optional than mandatory... I added some text commands to add effort more easily but there is more I could do here.
2) columnview dynamic block (in the works)
3) Some more table formulas - I don't quite have the ones required.
4) The ability to pipe a table to a gnu plot script block - going to be the bulk of the work and will be part of the foundational work for that babel stuff I was talking about.

Going to take me a bit to get to number 4. You are very much welcome to help wherever you would like or work on your own things. We can hopefully come up with a way to communicate as we go forward.

**Comment by Anti-Distinctlyminty** [comment] 2021-03-10 09:40
> Okay, so my clone is here:
> C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\OrgExtended
> 
NOTE the capitalization, it matters... I should really NOT have done that, but it's the way it is now.

So, I checked it out to the same location, just to be super explicit, my folder structure looks like this:
```
C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\OrgExtended
├───htmlstyles
├───images
├───messages
├───orgdynamic
├───orgparse
│   └───utils
├───orgresolver
├───orgsrc
├───orgutil
├───pandoc
├───readtheorg
└───snippets
```

> I just clone directly into that folder, dump an OrgExtended.sublime-package file in the root of that and away I go.

Sorry for the silly questions, but does the `OrgExtended.sublime-package` file come from installing the package itself and moving it from 
`C:\Users\Luke\AppData\Roaming\Sublime Text 3\Installed Packages` 
to
`C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\orgextended`?

**Comment by ihdavids** [comment] 2021-03-10 16:46
Ugh, okay, so that was a typo. I meant to say sublime-project file. 

A note about packages:
OrgExtended.sublime-package is the actual package, if you rename it to OrgExtended.zip it's just a zip file and you can look inside. It has some extra metadata that packagecontrol generated. You actually need to delete that package file or you will get errors as both the zipped version and the loose file version of the package are loaded.

The sublime-project file is for you. IE by placing that file there you can jump to that project when you want to work on it. Sorry that was a typo on my part. I was thinking about whether or not I should talk about deleting the package file.

**Comment by ihdavids** [comment] 2021-03-10 16:48
The project file is made just by doing the usual project thing in sublime. (NOTE I am using ST 4 not ST 3 for development so my menu bar looks a little different)

![image](https://user-images.githubusercontent.com/1059210/110665646-6e846e80-817d-11eb-8960-d3b9e030789f.png)

**Comment by ihdavids** [comment] 2021-03-10 17:01
Quick overview of the package: (There is a LOT of cruft in there, like I said I have been hacking and testing things for quite some time.)

orgsrc
orgresolver
orgdynamic 

Are source blocks, links and dynamic block handlers. They are not loaded by the main system but rather by orgextension.py

asettings.py is my simple settings module. It just wraps the sublime settings system and is used by almost everything.

I install TableEditor (a package) dynamically when you install org. It's not supported anymore but it is my favorite for handling tables, and it is simple so if I have to consume it I can in the future. packagecon.py exists so I can dynamically install a package on you.

orgparse / orgdb.py work hand in hand. orgparse is an external python library that I consumed, added a ton to and use. sublimenode.py in there are where I am trying to adde extensions to node that are sublime specific.

orgutil - As I get utility functions that are stable and I am not changing much anymore I try to promote them into there. The problem is that things in subfolders to not automatically get reloaded when you change them during development (you have to restart sublime) so things only move there once they are relatively stable and I am not testing / iterating on them. I have a bunch of extensions to the sublime view API in there that I use all over the place.

balloontip.ps1 / orgnotifications.py is my notifications system. It does a popup on windows. I think I did something to my notifications system recently, it is popping up when it shouldn't at the moment. I don't have an equivalent on mac at the moment. You just get the buffer not the external popup.

Syntax changes go in the OrgExtended.sublime-syntax-template and then you re-run the syntax gen command (which is commented out by default in the OrgExtended.sublime-commands file) That takes the contents of languagelist.yaml and generates the required syntax for all the languages listed in there.

Any other questions, do not hesitate to ask. Sublime packages are a bit of a black art to work on. There is a LOT of undocumented stuff about them that I have had to learn by experimentation, posting on forums, looking into other packages, or now the discord channel. I am happy to pass any of that learning on.

There is a LOT of mess in here to cleanup up. Please ask if something doesn't make sense or seems broken / messy.

**Comment by ihdavids** [comment] 2021-03-10 17:04
Oh, I do one REALLY crazy thing that is non sublime standard.
I have pymitter in this little system. I often find that I want to make some changes to the buffer, and then do something else. Like I might want to add some text and then rerun the TableEditor align method, but AFTER the edits happen. Text commands in sublime are put into a queue and execute "sometime" in the future. Soooo... I use pymitter to allow me to chain commands. I have this goofy pymitter onDone token you can pass to a TextCommand and then it will signal that token when done allowing me to run something "AFTER" that command is executed. I first ran into the need for this with properties where I was wanting to do things like run the property drawer system and then add a property to the drawer if it had been created.

**Comment by ihdavids** [comment] 2021-03-11 17:32
I have added a planning folder to the docs. Since you may be joining in on some things I figure it is time that I start keeping track of my goals and intentions in a more visible place.

From my side, I am driving towards a 1.2.0 release where I will remove the preview tag from tables. My target is that gantt chart video I sent the other day. I have sketched out my rough plan for the next little bit in there with some of the releases I think I will be targetting. (That could all change)

Feel free to edit that file with any of your thoughts and plans (if you have them) otherwise, it is there as a communication vehicle.

**Comment by Anti-Distinctlyminty** [comment] 2021-03-13 09:17
I added a `comms.org` file for direct communication. If that's not the way to do things we can try something else. But if that works we can close this issue,

**Comment by ihdavids** [comment] 2021-03-13 20:57
Sure, although you won't get notified when I change that file. Issues are an easy way for us to chat and get email about it.

**Comment by ihdavids** [comment] 2021-03-13 20:57
I responded in your comms doc and added some thoughts of my own. I am adding mini projects as I remember them as sort of backlog org documents in that folder.

**Comment by ihdavids** [comment] 2021-03-14 21:08
I just cut: 1.1.29
Lots of testing to do for 1.1.30 / 1.2.0 BUT the gantt chart demo kind of works now: 

https://github.com/ihdavids/orgextended_docs/blob/master/learning_gantt_example.org

More importantly, it has the super infant start of some babel work. IE: the gnuplot script block is tangling in a table as source.

**Closed as completed** 2021-05-03 02:40 UTC
